In [1]:
import tensorflow as tf

!conda install -y quandl

Collecting package metadata: ...working... done
Solving environment: ...working... done

# All requested packages already installed.

In [104]:
import quandl
quandl.ApiConfig.api_key = 'zMbt6sRnVyTnre9ih5k_'

stock_data = quandl.get_table('WIKI/PRICES', ticker = ['MSFT'],
 
                        date = { 'gte': '2010-12-31', 'lte': '2018-12-31' }, 
                        paginate=True)

In [105]:
stock_data = stock_data.iloc[::-1]

In [106]:
stock_data.head()

,ticker,date,open,high,low,close,volume,ex-dividend,split_ratio,adj_open,adj_high,adj_low,adj_close,adj_volume
None,,,,,,,,,,,,,,
1819,MSFT,2010-12-31,27.80,27.92,27.63,27.9100,24752000.0,0.0,1.0,23.062244,23.161793,22.921216,23.153497,24752000.0
1818,MSFT,2011-01-03,28.05,28.18,27.92,27.9800,53443800.0,0.0,1.0,23.269638,23.377483,23.161793,23.211568,53443800.0
1817,MSFT,2011-01-04,27.94,28.17,27.85,28.0875,54405600.0,0.0,1.0,23.178385,23.369187,23.103723,23.300747,54405600.0
1816,MSFT,2011-01-05,27.90,28.01,27.77,28.0000,58998700.0,0.0,1.0,23.145201,23.236455,23.037356,23.228159,58998700.0
1815,MSFT,2011-01-06,28.04,28.85,27.86,28.8200,88026300.0,0.0,1.0,23.261342,23.933300,23.112018,23.908412,88026300.0

In [107]:
stock_data = stock_data.reset_index()
stock_data.head()

,None,ticker,date,open,high,low,close,volume,ex-dividend,split_ratio,adj_open,adj_high,adj_low,adj_close,adj_volume
0,1819,MSFT,2010-12-31,27.80,27.92,27.63,27.9100,24752000.0,0.0,1.0,23.062244,23.161793,22.921216,23.153497,24752000.0
1,1818,MSFT,2011-01-03,28.05,28.18,27.92,27.9800,53443800.0,0.0,1.0,23.269638,23.377483,23.161793,23.211568,53443800.0
2,1817,MSFT,2011-01-04,27.94,28.17,27.85,28.0875,54405600.0,0.0,1.0,23.178385,23.369187,23.103723,23.300747,54405600.0
3,1816,MSFT,2011-01-05,27.90,28.01,27.77,28.0000,58998700.0,0.0,1.0,23.145201,23.236455,23.037356,23.228159,58998700.0
4,1815,MSFT,2011-01-06,28.04,28.85,27.86,28.8200,88026300.0,0.0,1.0,23.261342,23.933300,23.112018,23.908412,88026300.0

In [108]:
stock_shift = stock_data.shift(periods=1)
stock_shift.head()

,None,ticker,date,open,high,low,close,volume,ex-dividend,split_ratio,adj_open,adj_high,adj_low,adj_close,adj_volume
0,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1819.0,MSFT,2010-12-31,27.80,27.92,27.63,27.9100,24752000.0,0.0,1.0,23.062244,23.161793,22.921216,23.153497,24752000.0
2,1818.0,MSFT,2011-01-03,28.05,28.18,27.92,27.9800,53443800.0,0.0,1.0,23.269638,23.377483,23.161793,23.211568,53443800.0
3,1817.0,MSFT,2011-01-04,27.94,28.17,27.85,28.0875,54405600.0,0.0,1.0,23.178385,23.369187,23.103723,23.300747,54405600.0
4,1816.0,MSFT,2011-01-05,27.90,28.01,27.77,28.0000,58998700.0,0.0,1.0,23.145201,23.236455,23.037356,23.228159,58998700.0

In [77]:
stock_data.head()

,ticker,date,open,high,low,close,volume,ex-dividend,split_ratio,adj_open,adj_high,adj_low,adj_close,adj_volume,ret
None,,,,,,,,,,,,,,,
1818,MSFT,2011-01-03,28.05,28.18,27.92,27.9800,53443800.0,0.0,1.0,23.269638,23.377483,23.161793,23.211568,53443800.0,0.002505
1817,MSFT,2011-01-04,27.94,28.17,27.85,28.0875,54405600.0,0.0,1.0,23.178385,23.369187,23.103723,23.300747,54405600.0,0.003835
1816,MSFT,2011-01-05,27.90,28.01,27.77,28.0000,58998700.0,0.0,1.0,23.145201,23.236455,23.037356,23.228159,58998700.0,-0.003120
1815,MSFT,2011-01-06,28.04,28.85,27.86,28.8200,88026300.0,0.0,1.0,23.261342,23.933300,23.112018,23.908412,88026300.0,0.028865
1814,MSFT,2011-01-07,28.64,28.74,28.25,28.6000,73762000.0,0.0,1.0,23.759089,23.842046,23.435553,23.725905,73762000.0,-0.007663

In [73]:
stock_shift.head()

,ticker,date,open,high,low,close,volume,ex-dividend,split_ratio,adj_open,adj_high,adj_low,adj_close,adj_volume,ret
None,,,,,,,,,,,,,,,
1819,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1818,MSFT,2010-12-31,27.80,27.92,27.63,27.9100,24752000.0,0.0,1.0,23.062244,23.161793,22.921216,23.153497,24752000.0,0.002505
1817,MSFT,2011-01-03,28.05,28.18,27.92,27.9800,53443800.0,0.0,1.0,23.269638,23.377483,23.161793,23.211568,53443800.0,0.003835
1816,MSFT,2011-01-04,27.94,28.17,27.85,28.0875,54405600.0,0.0,1.0,23.178385,23.369187,23.103723,23.300747,54405600.0,-0.003120
1815,MSFT,2011-01-05,27.90,28.01,27.77,28.0000,58998700.0,0.0,1.0,23.145201,23.236455,23.037356,23.228159,58998700.0,0.028865

In [109]:
import numpy as np 
ret =[]

stock_data['ret'] = np.log(stock_data['close']) - np.log(stock_shift['close'])

#stock_shift.head()

stock_data= stock_data.drop([0])

(1819, 15)

In [110]:
stock_shift = stock_data

In [111]:
train_size = int(len(stock_shift)*0.90)
test_size = len(stock_shift) - train_size

train ,test   = stock_shift.iloc[0:train_size] , stock_shift.iloc[train_size:len(stock_shift)]

In [112]:
train.head()

,None,ticker,date,open,high,low,close,volume,ex-dividend,split_ratio,adj_open,adj_high,adj_low,adj_close,adj_volume,ret
1,1818,MSFT,2011-01-03,28.05,28.18,27.92,27.9800,53443800.0,0.0,1.0,23.269638,23.377483,23.161793,23.211568,53443800.0,0.002505
2,1817,MSFT,2011-01-04,27.94,28.17,27.85,28.0875,54405600.0,0.0,1.0,23.178385,23.369187,23.103723,23.300747,54405600.0,0.003835
3,1816,MSFT,2011-01-05,27.90,28.01,27.77,28.0000,58998700.0,0.0,1.0,23.145201,23.236455,23.037356,23.228159,58998700.0,-0.003120
4,1815,MSFT,2011-01-06,28.04,28.85,27.86,28.8200,88026300.0,0.0,1.0,23.261342,23.933300,23.112018,23.908412,88026300.0,0.028865
5,1814,MSFT,2011-01-07,28.64,28.74,28.25,28.6000,73762000.0,0.0,1.0,23.759089,23.842046,23.435553,23.725905,73762000.0,-0.007663

In [113]:
test.head()

,None,ticker,date,open,high,low,close,volume,ex-dividend,split_ratio,adj_open,adj_high,adj_low,adj_close,adj_volume,ret
1638,181,MSFT,2017-07-06,68.27,68.78,68.12,68.57,20776555.0,0.0,1.0,67.566308,68.071051,67.417854,67.863216,20776555.0,-0.007410
1639,180,MSFT,2017-07-07,68.70,69.84,68.70,69.46,15897154.0,0.0,1.0,67.991876,69.120125,67.991876,68.744042,15897154.0,0.012896
1640,179,MSFT,2017-07-10,69.46,70.25,69.20,69.98,14903400.0,0.0,1.0,68.744042,69.525899,68.486722,69.258682,14903400.0,0.007458
1641,178,MSFT,2017-07-11,70.00,70.68,69.75,69.99,16880205.0,0.0,1.0,69.278476,69.951467,69.031053,69.268579,16880205.0,0.000143
1642,177,MSFT,2017-07-12,70.69,71.28,70.55,71.15,17382861.0,0.0,1.0,69.961364,70.545283,69.822807,70.416623,17382861.0,0.016438

In [114]:
X_train = []
Y_train = []

X_test = []
Y_test = []

for i in range(60,1637):
    X_train.append(train['ret'][i-60:i])
    Y_train.append(train['ret'][i])

for i in range(1638+60,(len(train)+len(test))):
    X_test.append(test['ret'][i-60:i])
    Y_test.append(test['ret'][i])

X_train,Y_train = np.array(X_train),np.array(Y_train)

X_test,Y_test = np.array(X_test),np.array(Y_test)

In [118]:
train.head(60)

,None,ticker,date,open,high,low,close,volume,ex-dividend,split_ratio,adj_open,adj_high,adj_low,adj_close,adj_volume,ret
1,1818,MSFT,2011-01-03,28.050,28.1800,27.9200,27.9800,53443800.0,0.00,1.0,23.269638,23.377483,23.161793,23.211568,53443800.0,0.002505
2,1817,MSFT,2011-01-04,27.940,28.1700,27.8500,28.0875,54405600.0,0.00,1.0,23.178385,23.369187,23.103723,23.300747,54405600.0,0.003835
3,1816,MSFT,2011-01-05,27.900,28.0100,27.7700,28.0000,58998700.0,0.00,1.0,23.145201,23.236455,23.037356,23.228159,58998700.0,-0.003120
4,1815,MSFT,2011-01-06,28.040,28.8500,27.8600,28.8200,88026300.0,0.00,1.0,23.261342,23.933300,23.112018,23.908412,88026300.0,0.028865
5,1814,MSFT,2011-01-07,28.640,28.7400,28.2500,28.6000,73762000.0,0.00,1.0,23.759089,23.842046,23.435553,23.725905,73762000.0,-0.007663
6,1813,MSFT,2011-01-10,28.260,28.4000,28.0400,28.2200,57573600.0,0.00,1.0,23.443849,23.559990,23.261342,23.410666,57573600.0,-0.013376
7,1812,MSFT,2011-01-11,28.200,28.2500,28.0500,28.1100,50298900.0,0.00,1.0,23.394075,23.435553,23.269638,23.319413,50298900.0,-0.003906
8,1811,MSFT,2011-01-12,28.120,28.5900,28.0700,28.5500,52631100.0,0.00,1.0,23.327708,23.717610,23.286230,23.684427,52631100.0,0.015532
9,1810,MSFT,2011-01-13,28.330,28.3900,28.0100,28.1900,67077600.0,0.00,1.0,23.501920,23.551694,23.236455,23.385779,67077600.0,-0.012690
10,1809,MSFT,2011-01-14,28.080,28.3800,27.9100,28.3000,62688400.0,0.00,1.0,23.294525,23.543398,23.153497,23.477032,62688400.0,0.003894
11,1808,MSFT,2011-01-18,28.160,28.7400,28.1400,28.6600,53322700.0,0.00,1.0,23.360891,23.842046,23.344300,23.775680,53322700.0,0.012641
12,1807,MSFT,2011-01-19,28.460,28.6800,28.2700,28.4700,50005900.0,0.00,1.0,23.609765,23.792272,23.452145,23.618060,50005900.0,-0.006652
13,1806,MSFT,2011-01-20,28.500,28.5500,28.1300,28.3525,58613600.0,0.00,1.0,23.642948,23.684427,23.336004,23.520585,58613600.0,-0.004136
14,1805,MSFT,2011-01-21,28.400,28.4300,28.0200,28.0200,58080300.0,0.00,1.0,23.559990,23.584877,23.244751,23.244751,58080300.0,-0.011797
15,1804,MSFT,2011-01-24,28.020,28.5600,27.9900,28.3800,52047800.0,0.00,1.0,23.244751,23.692722,23.219863,23.543398,52047800.0,0.012766
16,1803,MSFT,2011-01-25,28.140,28.4500,28.1200,28.4500,42436600.0,0.00,1.0,23.344300,23.601469,23.327708,23.601469,42436600.0,0.002463
17,1802,MSFT,2011-01-26,28.510,28.9900,28.5000,28.7800,74628800.0,0.00,1.0,23.651243,24.049440,23.642948,23.875229,74628800.0,0.011533
18,1801,MSFT,2011-01-27,28.750,29.4600,28.4900,28.8700,146938600.0,0.00,1.0,23.850342,24.439342,23.634652,23.949891,146938600.0,0.003122
19,1800,MSFT,2011-01-28,28.895,28.9300,27.4500,27.7510,141249400.0,0.00,1.0,23.970631,23.999666,22.771892,23.021594,141249400.0,-0.039531
20,1799,MSFT,2011-01-31,27.770,27.9000,27.4200,27.7250,65029000.0,0.00,1.0,23.037356,23.145201,22.747004,23.000025,65029000.0,-0.000937
21,1798,MSFT,2011-02-01,27.800,28.0600,27.6100,27.9925,62810700.0,0.00,1.0,23.062244,23.277934,22.904624,23.221937,62810700.0,0.009602
22,1797,MSFT,2011-02-02,27.930,28.1100,27.8800,27.9400,45824000.0,0.00,1.0,23.170089,23.319413,23.128610,23.178385,45824000.0,-0.001877
23,1796,MSFT,2011-02-03,27.965,27.9700,27.5400,27.6500,60340100.0,0.00,1.0,23.199124,23.203272,22.846554,22.937807,60340100.0,-0.010434
24,1795,MSFT,2011-02-04,27.700,27.8400,27.5100,27.7700,40412200.0,0.00,1.0,22.979286,23.095427,22.821666,23.037356,40412200.0,0.004331
25,1794,MSFT,2011-02-07,27.800,28.3400,27.7900,28.1975,68980900.0,0.00,1.0,23.062244,23.510215,23.053948,23.392001,68980900.0,0.015277
26,1793,MSFT,2011-02-08,28.100,28.3400,28.0500,28.2825,34904200.0,0.00,1.0,23.311117,23.510215,23.269638,23.462515,34904200.0,0.003010
27,1792,MSFT,2011-02-09,28.190,28.2600,27.9100,27.9700,52905100.0,0.00,1.0,23.385779,23.443849,23.153497,23.203272,52905100.0,-0.011111
28,1791,MSFT,2011-02-10,27.930,27.9400,27.2900,27.5000,76672400.0,0.00,1.0,23.170089,23.178385,22.639159,22.813371,76672400.0,-0.016947
29,1790,MSFT,2011-02-11,27.760,27.8099,27.0700,27.2500,83939700.0,0.00,1.0,23.029061,23.070457,22.456652,22.605976,83939700.0,-0.009132
30,1789,MSFT,2011-02-14,27.205,27.2700,26.9500,27.2300,56766200.0,0.00,1.0,22.568645,22.622568,22.357103,22.589385,56766200.0,-0.000734
31,1788,MSFT,2011-02-15,27.040,27.3300,26.9500,26.9600,44116500.0,0.16,1.0,22.564891,22.806896,22.489786,22.498131,44116500.0,-0.009965
32,1787,MSFT,2011-02-16,27.050,27.0700,26.6000,27.0200,70817900.0,0.00,1.0,22.573236,22.589926,22.197711,22.548201,70817900.0,0.002223
33,1786,MSFT,2011-02-17,26.970,27.3700,26.9100,27.2100,57207300.0,0.00,1.0,22.506476,22.840276,22.456406,22.706756,57207300.0,0.007007
34,1785,MSFT,2011-02-18,27.130,27.2100,26.9900,27.0600,68667800.0,0.00,1.0,22.639996,22.706756,22.523166,22.581581,68667800.0,-0.005528
35,1784,MSFT,2011-02-22,26.780,27.1000,26.5200,26.5900,60889000.0,0.00,1.0,22.347921,22.614961,22.130951,22.189366,60889000.0,-0.017521
36,1783,MSFT,2011-02-23,26.530,26.8600,26.4300,26.5900,60234100.0,0.00,1.0,22.139296,22.414681,22.055846,22.189366,60234100.0,0.000000
37,1782,MSFT,2011-02-24,26.640,27.0600,26.5000,26.7700,64494200.0,0.00,1.0,22.231091,22.581581,22.114261,22.339576,64494200.0,0.006747
38,1781,MSFT,2011-02-25,26.910,26.9500,26.5000,26.5500,53006300.0,0.00,1.0,22.456406,22.489786,22.114261,22.155986,53006300.0,-0.008252
39,1780,MSFT,2011-02-28,26.690,26.8600,26.5100,26.5800,51379900.0,0.00,1.0,22.272816,22.414681,22.122606,22.181021,51379900.0,0.001129
40,1779,MSFT,2011-03-01,26.600,26.7800,26.1500,26.1600,60055000.0,0.00,1.0,22.197711,22.347921,21.822186,21.830531,60055000.0,-0.015928
41,1778,MSFT,2011-03-02,26.110,26.3700,26.0400,26.0775,48658200.0,0.00,1.0,21.788806,22.005776,21.730391,21.761685,48658200.0,-0.003159
42,1777,MSFT,2011-03-03,26.260,26.4000,26.1800,26.2000,68271500.0,0.00,1.0,21.913981,22.030811,21.847221,21.863911,68271500.0,0.004687
43,1776,MSFT,2011-03-04,26.220,26.2400,25.8000,25.9525,70437200.0,0.00,1.0,21.880601,21.897291,21.530111,21.657372,70437200.0,-0.009491
44,1775,MSFT,2011-03-07,26.130,26.2700,25.5500,25.7200,64980400.0,0.00,1.0,21.805496,21.922326,21.321486,21.463351,64980400.0,-0.008999
45,1774,MSFT,2011-03-08,25.770,26.0200,25.6500,25.9100,50549800.0,0.00,1.0,21.505076,21.713701,21.404936,21.621906,50549800.0,0.007360
46,1773,MSFT,2011-03-09,25.810,25.9800,25.6600,25.8900,39789100.0,0.00,1.0,21.538456,21.680321,21.413281,21.605216,39789100.0,-0.000772
47,1772,MSFT,2011-03-10,25.620,25.7100,25.3500,25.4100,66549500.0,0.00,1.0,21.379901,21.455006,21.154586,21.204656,66549500.0,-0.018714
48,1771,MSFT,2011-03-11,25.410,25.8500,25.3600,25.6800,49905800.0,0.00,1.0,21.204656,21.571836,21.162931,21.429971,49905800.0,0.010570
49,1770,MSFT,2011-03-14,25.490,25.7600,25.3500,25.6900,54473400.0,0.00,1.0,21.271416,21.496731,21.154586,21.438316,54473400.0,0.000389
50,1769,MSFT,2011-03-15,25.080,25.4700,25.0000,25.3900,76067300.0,0.00,1.0,20.929271,21.254726,20.862510,21.187966,76067300.0,-0.011746
51,1768,MSFT,2011-03-16,25.220,25.2800,24.6800,24.7900,100725400.0,0.00,1.0,21.046101,21.096171,20.595470,20.687265,100725400.0,-0.023915
52,1767,MSFT,2011-03-17,25.060,25.2200,24.7500,24.7800,62497000.0,0.00,1.0,20.912580,21.046101,20.653885,20.678920,62497000.0,-0.000403
53,1766,MSFT,2011-03-18,25.060,25.1800,24.7979,24.8000,85486700.0,0.00,1.0,20.912580,21.012721,20.693858,20.695610,85486700.0,0.000807
54,1765,MSFT,2011-03-21,25.180,25.5800,25.1500,25.3300,46878100.0,0.00,1.0,21.012721,21.346521,20.987686,21.137896,46878100.0,0.021146
55,1764,MSFT,2011-03-22,25.300,25.4600,25.2300,25.2950,30895600.0,0.00,1.0,21.112861,21.246381,21.054446,21.108688,30895600.0,-0.001383
56,1763,MSFT,2011-03-23,25.230,25.6100,25.1800,25.5400,43969000.0,0.00,1.0,21.054446,21.371556,21.012721,21.313141,43969000.0,0.009639
57,1762,MSFT,2011-03-24,25.600,25.8700,25.5000,25.8100,38696700.0,0.00,1.0,21.363211,21.588526,21.279761,21.538456,38696700.0,0.010516
58,1761,MSFT,2011-03-25,25.930,25.9500,25.5900,25.6200,57029800.0,0.00,1.0,21.638596,21.655286,21.354866,21.379901,57029800.0,-0.007389
59,1760,MSFT,2011-03-28,25.660,25.7200,25.3800,25.4100,48973200.0,0.00,1.0,21.413281,21.463351,21.179621,21.204656,48973200.0,-0.008230
60,1759,MSFT,2011-03-29,25.340,25.5200,25.3000,25.4900,40763500.0,0.00,1.0,21.146241,21.296451,21.112861,21.271416,40763500.0,0.003143

In [116]:
print(X_train)

[[ 0.00250492  0.00383467 -0.00312013 ... -0.00738872 -0.0082305
   0.00314342]
 [ 0.00383467 -0.00312013  0.02886508 ... -0.0082305   0.00314342
   0.00469668]
 [-0.00312013  0.02886508 -0.00766287 ...  0.00314342  0.00469668
  -0.0086275 ]
 ...
 [-0.00258969  0.00258969 -0.00076098 ... -0.01889279  0.00848865
  -0.01894626]
 [ 0.00258969 -0.00076098 -0.00228641 ...  0.00848865 -0.01894626
   0.00640375]
 [-0.00076098 -0.00228641 -0.0007633  ... -0.01894626  0.00640375
  -0.01108691]]

In [119]:
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))

In [120]:

from tensorflow.python import keras 
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers.core import Dense, Dropout
from tensorflow.python.keras.callbacks import History
from tensorflow.python.keras.layers.recurrent import LSTM
from tensorflow.python.keras.models import model_from_json
from tensorflow.python.keras.regularizers import l2

from tensorflow.python.keras import backend as K

regressor = Sequential()

regressor.add(LSTM(units = 50, return_sequences = True, input_shape = (x_train.shape[1], 1)))
regressor.add(Dropout(0.2))

regressor.add(LSTM(units = 50, return_sequences = True))
regressor.add(Dropout(0.2))

regressor.add(LSTM(units = 50, return_sequences = True))
regressor.add(Dropout(0.2))

regressor.add(LSTM(units = 50))
regressor.add(Dropout(0.2))

regressor.add(Dense(units = 1))

regressor.compile(optimizer = 'adam', loss = 'mean_squared_error')

regressor.fit(X_train, Y_train, epochs = 10, batch_size = 32)

Epoch 1/10
1577/1577 [==============================] - 14s 9ms/sample - loss: 2.2427e-04
Epoch 2/10
1577/1577 [==============================] - 9s 6ms/sample - loss: 2.1499e-04
Epoch 3/10
1577/1577 [==============================] - 8s 5ms/sample - loss: 2.1666e-04
Epoch 4/10
1577/1577 [==============================] - 8s 5ms/sample - loss: 2.1632e-04
Epoch 5/10
1577/1577 [==============================] - 8s 5ms/sample - loss: 2.1446e-04
Epoch 6/10
1577/1577 [==============================] - 9s 6ms/sample - loss: 2.1241e-04
Epoch 7/10
1577/1577 [==============================] - 8s 5ms/sample - loss: 2.1485e-04
Epoch 8/10
1577/1577 [==============================] - 9s 6ms/sample - loss: 2.1172e-04
Epoch 9/10
1577/1577 [==============================] - 9s 6ms/sample - loss: 2.1710e-04
Epoch 10/10
1577/1577 [==============================] - 9s 6ms/sample - loss: 2.1244e-04

In [121]:
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))
predicted_stock_price = regressor.predict(X_test)
predicted_stock_price = sc.inverse_transform(predicted_stock_price)

ValueError: Error when checking input: expected lstm_8_input to have shape (60, 1) but got array with shape (0, 1)

In [122]:
X_test.shape

(121, 0, 1)

In [ ]:
import matplotlib.pyplot as plt

plt.plot(Y_test, color = 'black', label = 'TATA Stock Price')
plt.plot(predicted_stock_price, color = 'green', label = 'Predicted TATA Stock Price')
plt.title('TATA Stock Price Prediction')
plt.xlabel('Time')
plt.ylabel('TATA Stock Price')
plt.legend()
plt.show()